spring:
  security:
    user:
      name: gunel
      password: gunel123
  datasource:
    url: jdbc:postgresql://localhost:5432/datingapp
    username: postgres
    password: gunel1969
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
server:
  port: 8088
jwt:
  secret: 70ea0ffa-bb6e-45ff-af18-58638854ae78
  expiration: 86400000